version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mobile_02      
    ports:
      - "5440:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
